### ISSUE TITLE
Protect admin views

### ISSUE THREAD

**Issue by jacquestardie** [jacquestardie/learning-journal#13]
Nothing is stopping attackers from submitting POST requests that will affect our databases. Jinja doesn't render the edit form unless you're authenticated, but hiding isn't protecting.

Pyramid provides a means of [protecting views with permission](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#protecting-views-with-permissions).

**Comment by jacquestardie** [comment]
More on [view security](http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/viewconfig.html#view-security-section)

**Comment by poolbath1** [comment]
https://github.com/jacquestardie/learning-journal/commit/441332bfcbf2380c82e6fb77e529626cc85db0f3 and https://github.com/jacquestardie/learning-journal/commit/133d69182b1e3cc18371d57890ae9187e0796b6b seem to take care of this, but needs more testing first

**Comment by poolbath1** [comment]
Admin views are now more secure.
