### ISSUE TITLE
Add Post: form should validate to require a title and body

### ISSUE THREAD

**Issue by poolbath1** [jacquestardie/learning-journal#16]
The entry should not post unless there is a title and body. You can't get to the detail page without a title.

**Comment by jacquestardie** [comment]
hey @poolbath1 thanks for all the suggestions, keep em coming

**Comment by poolbath1** [comment]
This is a low priority bug since the only user right now is just going to be the admin. If the admin messes it up, they'll have to go into the database directly to fix it. So that's annoying, but a low priority bug.
