### ISSUE TITLE
Format the date of a post to show local Seattle time instead of GMT (or both like reddit?)

### ISSUE THREAD

**Issue by poolbath1** [jacquestardie/learning-journal#22]
It could display "submitted X hours/or days ago" with a mouse-over tool-tip like reddit that shows the time it was submitted in GMT. Or at least just show when it was submitted in Seattle time.

**Comment by jacquestardie** [comment]
[Possible](http://jinja.pocoo.org/docs/dev/api/#custom-filters), but I'm going to keep these as is. Time of day isn't as important since posts will likely only ever go out once a day.
